
spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/mariadb-um-para-muitos2-atividade
    username: sa
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        '[format_sql]': true

server:
  servlet:
    context-path: /api

logging:
  level:
    '[br.com.zup.handora]': debug
